
name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install

      # Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
        
      # Cache Docker layers
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

      # Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
          
      # Build and push Docker image
    - name: Build and push Docker image
      env:
        DOCKER_BUILDKIT: 1
        IMAGE_NAME: saitej150/spring-boot-keycloak
        DOCKER_REGISTRY: docker.io
      run: |
        docker build -t $IMAGE_NAME .
        docker tag $IMAGE_NAME $DOCKER_REGISTRY/$IMAGE_NAME:${{ github.sha }}
        docker push $DOCKER_REGISTRY/$IMAGE_NAME:${{ github.sha }}